-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 21:15:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ptp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ptp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ptp` DEFAULT CHARACTER SET utf8 ;
USE `ptp` ;

-- -----------------------------------------------------
-- Table `Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subjects` (
  `subjects_id` INT NOT NULL AUTO_INCREMENT,
  `subjects` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subjects_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `department` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school` (
  `school_id` INT NOT NULL AUTO_INCREMENT,
  `school` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`school_id`))
ENGINE = InnoDB;

-- KJALSDFJLKASF
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `year_level` VARCHAR(45) NOT NULL,
  `course` VARCHAR(45) NOT NULL,
  `biography` VARCHAR(200) NOT NULL,
  `profile_picture` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_school_id_idx` (`school_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`school_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- KJALSDFJLKASF
-- -----------------------------------------------------
-- Table `Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `professors` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `profile_picture` VARCHAR(45) NULL,
  PRIMARY KEY (`professor_id`),
  INDEX `fk_department_id_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `fk_prof_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`school_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prof_department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subject_Professor_Link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subject_professor_link` (
  `professor_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  INDEX `fk_subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_subj_prof_link_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subjects` (`subjects_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subj_prof_link_professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `professors` (`professor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry` (
  `entry_id` INT NOT NULL AUTO_INCREMENT,
  `professor_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  `content` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`entry_id`),
  INDEX `fk_professor_id_idx` (`professor_id` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_entry_professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `professors` (`professor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entry_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vote` (
  `user_id` INT NOT NULL,
  `entry_id` INT NOT NULL,
  `vote` SMALLINT NOT NULL,
  PRIMARY KEY (`user_id`,`entry_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_entry_id_idx` (`entry_id` ASC) VISIBLE,
  CONSTRAINT `fk_vote_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vote_entry_id`
    FOREIGN KEY (`entry_id`)
    REFERENCES `entry` (`entry_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO school (school)
VALUES ('De La Salle University'), ('Ateneo De Manila'), ('University of The Philippines'), ('University de Santo Tomas'), ('Mapúa University');

INSERT INTO department(department)
VALUES ('IT'), ('Business'), ('Law'), ('Biology'), ('Engineering');

INSERT INTO subjects (subjects)
VALUES ('CCAPDEV'), ('ITNET04'), ('GEMATMW'), ('ACYMAG2'), ('INPLANT');